[OPENAI]
OPENAI_API_KEY = "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"

[google]
client_id = "173328178748-a2251vns2vbmjivi2j3ii5tvgg8kjn0v.apps.googleusercontent.com"
client_secret = "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"

[mongo]
db_uri = "mongodb+srv://leapadmin:sR7DhtEoSvQ5wp1g@leapcluster.csg2f.mongodb.net/"
db_name = "CMS"
collection_name = "StudentBotTest"